/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int sum(int a, int b){
        int c = a;
        int d = b;
        int sum = a * b;
        getGreeting();
        return a * b;
      
    }

    public static void main(String[] args) {
        
            int num = 789;
            int reversednum = 0;
            int remainder;
            while (num != 0) {
                remainder = num % 10;
                reversednum = reversednum * 10 + remainder;
                num /= 10;
            }
            System.out.println("Reversed number is "+ reversednum);
        }
    
    }

